;; -*- mode: eask; lexical-binding: t -*-

(package "macro-tools"
         "1.0.0"
         "Utilities for macros")

(website-url "https://github.com/jgrey4296/macro-tools")
(keywords )

(package-file "macro-tools.el")
(files "macro-tools--*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "cl-lib")
(depends-on "dash")
(depends-on "eieio")
(depends-on "f")
(depends-on "s")
(depends-on "transient")
