;; -*- mode: eask; lexical-binding: t -*-

(package "macro-tools"
         "1.0.0"
         "Utilities for macros")

(website-url "https://github.com/jgrey4296/macro-tools")
(keywords )

(package-descriptor "macro-tools-pkg.el")
(files "./macro-tools.el" "./macro-tools--*.el")


(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "cl-lib" "1.0")
(depends-on "dash" "2.20.0")
(depends-on "eieio" "1.4")
(depends-on "s" "1.13.1")
